--
-- Create Schema Script 
--   Database Version   : 10.2.0.1.0 
--   TOAD Version       : 9.0.1.8 
--   DB Connect String  : XE 
--   Schema             : LEADQUIEZS 
--   Script Created by  : SYS 
--   Script Created at  : 11/3/2018 11:04:27 PM 
--   Physical Location  :  
--   Notes              :  
--

-- Object Counts: 
--   Indexes: 13        Columns: 14         
--   Sequences: 5 
--   Tables: 5          Columns: 24         Constraints: 9      


CREATE SEQUENCE USER_USERID
  START WITH 30
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE ANSWER_ANSWERID
  START WITH 157
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE OUTCOME_OUTCOMEID
  START WITH 87
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE QUESTION_QUESTIONID
  START WITH 143
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE QUIEZ_QUIEZID
  START WITH 83
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE TABLE QUESTIONS
(
  QUESTION_ID    NUMBER(10)                     NOT NULL,
  QUESTION_NAME  VARCHAR2(100 BYTE)             NOT NULL,
  QUIEZ_ID       NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE OUTCOMES
(
  OUTCOME_ID         NUMBER(10)                 NOT NULL,
  OUTCOME_DESCRPION  VARCHAR2(4000 BYTE),
  OUTCOME_TITLE      VARCHAR2(100 BYTE)         NOT NULL,
  QUIEZ_ID           NUMBER(10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE ANSWERS
(
  ANSWER_TYPE  VARCHAR2(31 BYTE)                NOT NULL,
  ANSWER_ID    NUMBER(10)                       NOT NULL,
  ANSWER       VARCHAR2(100 BYTE)               NOT NULL,
  OUTCOMETYPE  VARCHAR2(255 BYTE),
  IMAGE        VARCHAR2(20 BYTE),
  OUTCOME_ID   NUMBER(10)                       NOT NULL,
  QUESTION_ID  NUMBER(10)                       NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE QUIEZS
(
  QUIEZ_ID         NUMBER(10)                   NOT NULL,
  QUIEZ_DESCRPION  VARCHAR2(4000 CHAR),
  QUIEZ_IMAGE      VARCHAR2(100 CHAR)           NOT NULL,
  QUIEZ_LABEL      VARCHAR2(100 CHAR)           NOT NULL,
  QUIEZ_NAME       VARCHAR2(100 CHAR)           NOT NULL,
  QUIEZ_TITLE      VARCHAR2(400 CHAR)           NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE TABLE USERS
(
  USER_ID        NUMBER(10)                     NOT NULL,
  USER_EMAIL     VARCHAR2(100 CHAR)             NOT NULL,
  USER_USERNAME  VARCHAR2(100 CHAR)             NOT NULL,
  USER_PASWWORD  VARCHAR2(100 CHAR)             NOT NULL
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX QUESTION_NAME_QUIEZID_UK ON QUESTIONS
(QUESTION_NAME, QUIEZ_ID)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX UK_GKG8QI5GFBT7WKKN45AD03GKY ON QUESTIONS
(QUESTION_NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX UK_N9BN1NUJGOO8N106IDCOVJGHK ON OUTCOMES
(OUTCOME_TITLE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX UK_PEFEGAOSAUA7NVIBY7U91W2IH ON ANSWERS
(ANSWER)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX UK_R8EJBBWSWPLM87R8B1XDS32I9 ON QUIEZS
(QUIEZ_TITLE)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX UK_JW57A11IJQS8R667Y4NDDMDFM ON QUIEZS
(QUIEZ_NAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX UK_9RA8WLF0EVEAGQP8H0QA7TVJ7 ON USERS
(USER_USERNAME)
LOGGING
NOPARALLEL;


CREATE UNIQUE INDEX UK_49IJLI02S2E0RV26L647LYA41 ON USERS
(USER_EMAIL)
LOGGING
NOPARALLEL;


ALTER TABLE QUESTIONS ADD (
  PRIMARY KEY
 (QUESTION_ID));

ALTER TABLE OUTCOMES ADD (
  PRIMARY KEY
 (OUTCOME_ID));

ALTER TABLE ANSWERS ADD (
  PRIMARY KEY
 (ANSWER_ID));

ALTER TABLE QUIEZS ADD (
  PRIMARY KEY
 (QUIEZ_ID));

ALTER TABLE USERS ADD (
  PRIMARY KEY
 (USER_ID));

ALTER TABLE QUESTIONS ADD (
  CONSTRAINT FK_LFYXLL4H9DJ4WEAN8O16BAKQ2 
 FOREIGN KEY (QUIEZ_ID) 
 REFERENCES QUIEZS (QUIEZ_ID));

ALTER TABLE OUTCOMES ADD (
  CONSTRAINT FK_T1A4TLE1MG0QRE183XEXHK1OI 
 FOREIGN KEY (QUIEZ_ID) 
 REFERENCES QUIEZS (QUIEZ_ID));

ALTER TABLE ANSWERS ADD (
  CONSTRAINT FK_ONBCR8P3JAH9WBW8565L18VGV 
 FOREIGN KEY (OUTCOME_ID) 
 REFERENCES OUTCOMES (OUTCOME_ID),
  CONSTRAINT FK_4LG71U66M4WQWRLES1TMPW81B 
 FOREIGN KEY (QUESTION_ID) 
 REFERENCES QUESTIONS (QUESTION_ID));

